### ISSUE TITLE
[config file] Ambiguous filter name

### ISSUE THREAD

**Issue by lpofredc** [dthonon/Client_API_VN#289]
`territorial_unit_ids` filter name is quite ambiguous. API use the territory short_name, not the territory id. 

| name | id | short_name |
| :--- | :--- | :--- |
| Ain | 1 | 01 |
| Aisne | 2 | 02 |
| Allier | 3 | 03 |
| Alpes-de-Haute-Provence | 4 | 04 |
| Hautes-Alpes | 5 | 05 |
| Alpes-Maritimes | 6 | 06 |
| Ardèche | 7 | 07 |
| Ardennes | 8 | 08 |
| Ariège | 9 | 09 |
| Aube | 10 | 10 |
| Aude | 11 | 11 |
| Aveyron | 12 | 12 |
| Bouches-du-Rhône | 13 | 13 |
| Calvados | 14 | 14 |
| Cantal | 15 | 15 |
| Charente | 16 | 16 |
| Charente-Maritime | 17 | 17 |
| Cher | 18 | 18 |
| Corrèze | 19 | 19 |
| Corse-du-Sud | 20 | 2A |
| Haute-Corse | 21 | 2B |
| Côte-d'Or | 22 | 21 |
| Côtes-d'Armor | 23 | 22 |
| Creuse | 24 | 23 |
| Dordogne | 25 | 24 |
| Doubs | 26 | 25 |
| Drôme | 27 | 26 |
| Eure | 28 | 27 |
| Eure-et-Loir | 29 | 28 |
| Finistère | 30 | 29 |
| Gard | 31 | 30 |
| Haute-Garonne | 32 | 31 |
| Gers | 33 | 32 |
| Gironde | 34 | 33 |
| Hérault | 35 | 34 |
| Ille-et-Vilaine | 36 | 35 |
| Indre | 37 | 36 |
| Indre-et-Loire | 38 | 37 |
| Isère | 39 | 38 |
| Jura | 40 | 39 |
| Landes | 41 | 40 |
| Loir-et-Cher | 42 | 41 |
| Loire | 43 | 42 |
| Haute-Loire | 44 | 43 |
| Loire-Atlantique | 45 | 44 |
| Loiret | 46 | 45 |
| Lot | 47 | 46 |
| Lot-et-Garonne | 48 | 47 |
| Lozère | 49 | 48 |
| Maine-et-Loire | 50 | 49 |
| Manche | 51 | 50 |
| Marne | 52 | 51 |
| Haute-Marne | 53 | 52 |
| Mayenne | 54 | 53 |
| Meurthe-et-Moselle | 55 | 54 |
| Meuse | 56 | 55 |
| Morbihan | 57 | 56 |
| Moselle | 58 | 57 |
| Nièvre | 59 | 58 |
| Nord | 60 | 59 |
| Oise | 61 | 60 |
| Orne | 62 | 61 |
| Pas-de-Calais | 63 | 62 |
| Puy-de-Dôme | 64 | 63 |
| Pyrénées-Atlantiques | 65 | 64 |
| Hautes-Pyrénées | 66 | 65 |
| Pyrénées-Orientales | 67 | 66 |
| Bas-Rhin | 68 | 67 |
| Haut-Rhin | 69 | 68 |
| Rhône | 70 | 69 |
| Haute-Saône | 71 | 70 |
| Saône-et-Loire | 72 | 71 |
| Sarthe | 73 | 72 |
| Savoie | 74 | 73 |
| Haute-Savoie | 75 | 74 |
| Paris | 76 | 75 |
| Seine-Maritime | 77 | 76 |
| Seine-et-Marne | 78 | 77 |
| Yvelines | 79 | 78 |
| Deux-Sèvres | 80 | 79 |
| Somme | 81 | 80 |
| Tarn | 82 | 81 |
| Tarn-et-Garonne | 83 | 82 |
| Var | 84 | 83 |
| Vaucluse | 85 | 84 |
| Vendée | 86 | 85 |
| Vienne | 87 | 86 |
| Haute-Vienne | 88 | 87 |
| Vosges | 89 | 88 |
| Yonne | 90 | 89 |
| Territoire de Belfort | 91 | 90 |
| Essonne | 92 | 91 |
| Hauts-de-Seine | 93 | 92 |
| Seine-Saint-Denis | 94 | 93 |
| Val-de-Marne | 95 | 94 |
| Val-d'Oise | 96 | 95 |
| Manche Est | 110 | ME |
| Océan Atlantique | 111 | OA |
| Méditerranée | 112 | MD |
| Golfe de Gascogne | 113 | GG |
| Manche Ouest | 114 | MO |

**Comment by dthonon** [comment]
The name comes from the [API](https://www.faune-aura.org/index.php?m_id=43&hw=/observations), which is misleading, I agree. I can change the name in the config file, but that would require an update of existing config file. I prefer to add a comment in the config file explaining that it should be the short_name.
