### ISSUE TITLE
Docker : documentation

### ISSUE THREAD

**Issue by mgageo** [dthonon/Client_API_VN#317]
Bonjour,
Je viens de tester une installation Docker.

Après lancement de l'instance, je n'ai aucun serveur postgresql qui tourne

`root@e2f2d6f11b98:~# ss -tulw
Netid              State              Recv-Q              Send-Q                           Local Address:Port                             Peer Address:Port
root@e2f2d6f11b98:~#`

**Comment by lpofredc** [comment]
Bonour @mgageo,

L'image docker ne contient pas de serveur PostgreSQL, juste un client. Pour un déploiement docker de l'appli avec une bdd PostgreSQL, il faut par exemple les déployer dans une stack via docker compose.

**Comment by mgageo** [comment]
Merci pour la réponse, cela mériterait peut-être d'être préciser dans la documentation.
