### ISSUE TITLE
table forms : origine des coordonnées

### ISSUE THREAD

**Issue by mgageo** [dthonon/Client_API_VN#318]
Bonsoir,
Dans cette table, il y a 4 attributs de type coordonnée (coord_lat, coord_lon, coord_x_local, coord_y_local).
Comment sont déterminés ces valeurs ?
Dans le cadre des EPOC-ODF (par exemple EPOC-ODF_108580_Reserve le 07/03/2023), trois replicas sont effectués sur le même point. Les coordonnées devraient être identiques à quelques mètres prêt.

**Comment by dthonon** [comment]
Bonjour Marc,

Coord_lat et coord_lon proviennent directement du JSON téléchargé. Les 2
autres sont reprojetés à  partir des 2 téléchargées.

Daniel Thonon
+33 6 75 29 18 94
