### ISSUE TITLE
Données module colonie

### ISSUE THREAD

**Issue by lpojgc** [dthonon/Client_API_VN#333]
Je note ici pour faciliter ton suivi ;-) Il semble qu'on ne puisse pas récupérer les données du module colonie par l'API, est-ce effectivement le cas ?
Merci !

**Comment by dthonon** [comment]
Les données du module colonie sont pourtant bien téléchargées. Par exemple :
`                                "extended_info": {
                                    "colony": {
                                        "couples": "18",
                                        "nests": "18",
                                        "nests_is_min": "1"
                                    },
                                    "colony_extended": {
                                        "couples": "18",
                                        "nb_natural_nests": "18",
                                        "nb_natural_nests_is_min": "1"
                                    }
                                },
`

**Comment by lpojgc** [comment]
Effectivement, je les retrouve sur une donnée que je viens de regarder... Je comprends pas... mais tant mieux !
